### ISSUE TITLE
Fix the OG tags

### ISSUE THREAD

**Issue by Jai-Marothiya** [Jai-Marothiya/AlgoHub#16]
# Description

* While sharing AlgoHunt URL on any social media currently we get reactjs icon but actually it should be AlgoHunt logo. So it will be easily fix by adding OG tags.

![image](https://github.com/user-attachments/assets/1bae5d40-521c-43db-b939-48df2c5600d8)

**Comment by shutter-codes** [comment]
Hi,

I noticed that sharing AlgoHunt's URL on social media shows the ReactJS icon instead of the AlgoHunt logo. This can be fixed by adding Open Graph (OG) tags to ensure the correct logo and metadata are displayed.

I’d be happy to submit a pull request with the necessary changes if that works for you.

Best,
Naitik Sharma

**Comment by Jai-Marothiya** [comment]
Sure Naitik, I'll assign this issue to you.

**Comment by Jai-Marothiya** [comment]
> Sure Naitik, I'll assign this issue to you.

Also mark star to this repo.

**Comment by shutter-codes** [comment]
Hey,
Please provide the png of the logo to add

**Comment by shutter-codes** [comment]
Thanks, I have fix this issue will raise a pull request shortly till then can you please share the db.sql file to fix another issue.

**Comment by Jai-Marothiya** [comment]
> Thanks, I have fix this issue will raise a pull request shortly till then can you please share the db.sql file to fix another issue.
o
Thanks, Naitik - Please raise the PR after 1st October so that it will count for both of us in Hactoberfest2k24. I added backup.sql in contributing.md file and also added .env setup details there. You may pull changes and continue your work. If you need any kind of help, please let me know.

**Comment by shutter-codes** [comment]
Sure Thanks a lot Jai.

**Comment by Jai-Marothiya** [comment]
@shutter-codes  - Did you raised PR related to this issue? If yes then link it with this issue first, because I see one PR that is closed?

**Comment by shutter-codes** [comment]
Hey i have raised a PR for  issue  - #16
kindly please accept.
